name: Static Analysis

on:
    push:
      branches: [ main ]
jobs:
  phpstan:
    name: phpstan
    runs-on: ubuntu-latest
    steps:

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            password: ${{ secrets.SSHKEY }}
            script: cd /var/www/html && git pull origin main
